name: imako_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  minio: ^3.5.7
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.8.0
  timeago: ^3.7.1
  photo_view: ^0.15.0
  video_player: ^2.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_icons.png"