// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQhhiOVk6N2hs2Frv74FECCvM9yb_k7T8',
    appId: '1:1010775404756:web:e2f8a9b9a8c6e81d384b41',
    messagingSenderId: '1010775404756',
    projectId: 'imako-aaaf9',
    authDomain: 'imako-aaaf9.firebaseapp.com',
    storageBucket: 'imako-aaaf9.firebasestorage.app',
    measurementId: 'G-5S2CB2Q7ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCNTaVwyDeVCuhuThXYsdrEyOsBPjTQiw',
    appId: '1:1010775404756:android:4c386cb27f38ba16384b41',
    messagingSenderId: '1010775404756',
    projectId: 'imako-aaaf9',
    storageBucket: 'imako-aaaf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqxVXAMew4aeTPhx2j-msG9gJJBqXZqQ',
    appId: '1:1010775404756:ios:3fcf625db1862c10384b41',
    messagingSenderId: '1010775404756',
    projectId: 'imako-aaaf9',
    storageBucket: 'imako-aaaf9.firebasestorage.app',
    iosBundleId: 'com.example.imakoApp',
  );
}
